apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbum7
  labels:
    app: bookalbum7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbum7
  template:
    metadata:
      labels:
        app: bookalbum7
    spec:
      containers:
      - name: bookalbum7
        image: sreedocker123/bookmoviealbum:latest
        ports:
        - containerPort: 80
