apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbum1
  labels:
    app: bookalbum1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbum1
  template:
    metadata:
      labels:
        app: bookalbum1
    spec:
      containers:
      - name: bookalbum1
        image: sreedocker123/bookmoviealbum:latest
        ports:
        - containerPort: 80
