apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbum6
  labels:
    app: bookalbum6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbum6
  template:
    metadata:
      labels:
        app: bookalbum6
    spec:
      containers:
      - name: bookalbum6
        image: sreedocker123/bookmoviealbum:latest
        ports:
        - containerPort: 80
