apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookalbum1
  name: bookalbum1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bookalbum1

